#  █████╗ ██╗      █████╗  ██████╗██████╗ ██╗████████╗████████╗██╗   ██╗
# ██╔══██╗██║     ██╔══██╗██╔════╝██╔══██╗██║╚══██╔══╝╚══██╔══╝╚██╗ ██╔╝
# ███████║██║     ███████║██║     ██████╔╝██║   ██║      ██║    ╚████╔╝ 
# ██╔══██║██║     ██╔══██║██║     ██╔══██╗██║   ██║      ██║     ╚██╔╝  
# ██║  ██║███████╗██║  ██║╚██████╗██║  ██║██║   ██║      ██║      ██║   
# ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝╚═╝   ╚═╝      ╚═╝      ╚═
# →-.   →  .-'.   →  .--.   →  .--.   →  .--.   →  .-→
# →::.\::::::::.\::::::::.\::::::::.\::::::::.\::::::: → → 
# → →:.\ https://github.com/nosvagor/.dotfiles \::: → →  →  → 
# →::::.\::::::::.\::::::::.\::::::::.\::::::::.\::::→  →
#   → →   `--'  →   `.-'  →   `--'  →   `--'  →   `--' → → 

# Window padding (changes require restart)
window:
  x: 8
  y: 8

font:
  normal:
    family: Hack Nerd Font
    style: Regular
      
  italic:
    family: Hack Nerd Font
    style: Italic

  bold:
    family: Hack Nerd Font
    style: Bold
  
  bold_itaic:
    family: Hack Nerd Font
    style: Bold Italic

  size: 12

# Colors (Iceberg Dark)
colors:
  primary:
    background: '#161821'
    foreground: '#d2d4de'

  normal:
    black:   '#161821'
    red:     '#e27878'
    green:   '#b4be82'
    yellow:  '#e2a478'
    blue:    '#84a0c6'
    magenta: '#a093c7'
    cyan:    '#89b8c2'
    white:   '#c6c8d1'

  bright:
    black:   '#6b7089'
    red:     '#e98989'
    green:   '#c0ca8e'
    yellow:  '#e9b189'
    blue:    '#91acd1'
    magenta: '#ada0d3'
    cyan:    '#95c4ce'
    white:   '#d2d4de'

mouse: 
  hide_when_typing: true
