bold = true
color_mode = "ansi" # ansi, rgb or none
palette = "default" # default, darker, pastel or matrix
rainbow = 0 # 0-255
delay_ms = 16
inherit_style = false
kinds = ["heavy", "curved"] # heavy, light, curved, knobby, emoji, outline, dots, blocks, sus
num_pipes = 2
reset_threshold = 0.42 # 0.0–1.0
turn_chance = 0.15 # 0.0–1.0
